baseURL = "https://passerbycat.netlify.app/"

# 更改hugo當前預設使用的主題
theme = "LoveIt"

# 網站標題
title = "路人貓的小屋"

# 網站語言
languageCode = "zh-tw"
# 語言名稱
languageName = "繁體中文"
# 是否包含中日韓文字
hasCJKLanguage = true

# 默认每页列表显示的文章数目
paginate = 12
# 谷歌分析代号 [UA-XXXXXXXX-X]
googleAnalytics = ""
# 版权描述，仅仅用于 SEO
copyright = ""

# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true

# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# 作者配置
[author]
  name = "路人貓"
  email = ""
  link = ""

# 菜單配置
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1
    # 你可以在名稱（允許html格式）之前添加其他訊息，例如圖示
    pre = ""
    # 你可以在名稱（允許html格式）之前添加其他訊息，例如圖示
    post = ""
    # 當鼠標停在此處時，顯示的標題
    title = ""
  
  [[menu.main]]
    identifier = "book"
    name = "Books"
    url = "/book/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
  defaultTheme = "auto" # 預設的網站主題樣式["auto", "light", dark"]

  [params.home]
    rss = 10

    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = ""
      subtitle = "歡迎來到路人貓的小屋"

  [params.header.title]
    logo = ""
    name = "路人貓的小屋"
    pre = ""
    post = ""
    typeit = false

[outputs]
  home = ["HTML", "RSS", "Algolia"]

  [outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true
  
[params.search]
  enable = true
  # 搜索引擎的类型 ["lunr", "algolia"]
  type = "algolia"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = ""
  # LoveIt 新增 | 0.2.1 最大结果数目
  maxResultLength = 10
  # LoveIt 新增 | 0.2.3 结果内容片段长度
  snippetLength = 50
  # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [params.search.algolia]
    index = "my_index"
    appID = "L1WEB26MB8"
    searchKey = "9f9aea9d9fe43c35aab7a54bcc7e336b"