[build]
  publish = "public"
  command = "hugo --gc --minify && npm install atomic-algolia --save-dev && npm run algolia"

[context.production.environment]
  HUGO_VERSION = "0.129.0"
  HUGO_ENV = "production"